### ISSUE TITLE
ELB cannot be attached to multiple subnets in the same AZ

### ISSUE THREAD

**Issue by moesy** [BigDataBoutique/elasticsearch-cloud-deploy#25]
Current Setup:
- VPC in us-east-1
- private & public subnet in each availability zone

When explicitly specifying a list of availability zones through the "availability_zone" variable and subsequently defining the private subnets in those associated zones deployment through the "vpc_subnets" variable  fails with the message below: 

```
1 error(s) occurred:

* aws_elb.es_client_lb: 1 error(s) occurred:

* aws_elb.es_client_lb: InvalidConfigurationRequest: ELB cannot be attached to multiple subnets in the same AZ.
	status code: 409, request id:
```

This is likely due to vpc subnets being pulled automatically from the VPC and availability_zone variable not being respected. Unless it is a design feature that needs to be documented. 

workaround:
- Delete all public subnets form VPC
- Deploy ES using terraform scripts
- Reconfigure public subnets

**Comment by synhershko** [comment]
The `availability_zones` variable should have been removed because we now pull this data as `data`. Would using those available zones work in your case or do you need to specify a subset of AZs?

**Comment by mokio8** [comment]
@synhershko, unfortunately, the way data pulls currently it does not differentiate between public and private subnets hence the error where multiple subnets from the same AZ are being used.

**Comment by pranas** [comment]
> The availability_zones variable should have been removed because we now pull this data as data. 

In my case I went the opposite way and removed pulling availability_zones and subnets as data. We had subnets in our VPC I didn't want to use here so I made another var for subnets. I think this approach covers more use cases, would you merge it in if I open PR?

**Comment by synhershko** [comment]
@pranas sure, how would that work though? pulling AZs via data only if no var value was specified?

**Comment by pranas** [comment]
You could do the same thing as you did with AZs [here](https://github.com/synhershko/elasticsearch-cloud-deploy/blob/master/terraform-aws/datas.tf#L12). However, I actually went the stupid simple way by just requiring putting subnets in variables. I even deleted the forementioned code and require AZs in variables as well to make things simpler.

**Comment by tomerleib** [comment]
I was able to overcome this issue with by separating it to two different sections filtered by tag, so the ELB will be created using the correct public subnets and the instances will be created in the private subnets:
`data "aws_subnet_ids" "public" {`
 ` vpc_id = "${data.aws_vpc.selected.id}"`
`  filter {`
`    name = "tag:public"`
`    values = [""]`
`  }`
`}`

`data "aws_subnet_ids" "private" {`
`  vpc_id = "${data.aws_vpc.selected.id}"`
`  filter {`
`    name = "tag:private"`
`    values = [""]`
`  }`
`}`

**Comment by cwarny** [comment]
I'm facing this problem as well. What is the recommended workaround?

**Comment by cwarny** [comment]
@tomerleib I'm trying your workaround but could you elaborate as to how to modify the other files after implementing the change mentioned above?

**Comment by synhershko** [comment]
Fixed by https://github.com/BigDataBoutique/elasticsearch-cloud-deploy/commit/f776fb5807a31ea73234852974c1d000f74fece3
