### ISSUE TITLE
auth failure when xpack enabled

### ISSUE THREAD

**Issue by vanillagranilla** [BigDataBoutique/elasticsearch-cloud-deploy#38]
Testing out the repo (single node, AWS), and things work fine when variable "security_enabled" is "false".  Setting it to true and enabling xpack and I'm unable to log in with exampleuser credentials:

`{"statusCode":401,"error":"Unauthorized","message":"[security_exception] unable to authenticate user [exampleuser] for REST request [/_xpack/security/_authenticate], with { header={ WWW-Authenticate=\"Basic realm=\\\"security\\\" charset=\\\"UTF-8\\\"\" } }"}`

For reference, I'm running terraform v0.11.5.  I'm relatively new to elasticsearch, so forgive me if this is expected.  I tried configuring xpack security per the document below, but did not have any success.

https://www.elastic.co/guide/en/x-pack/current/security-getting-started.html

Please let me know if I can post any additional information to help.

**Comment by synhershko** [comment]
The exampleuser credentials are only valid with the nginx proxy, not with Kibana / Elasticsearch itself. Have you tried following the guide you linked to with the elastic user?

**Comment by synhershko** [comment]
Fixed via #84 (switching to the now free X-Pack Security)
