### ISSUE TITLE
question about formatting with terraform fmt 

### ISSUE THREAD

**Issue by kostyrev** [BigDataBoutique/elasticsearch-cloud-deploy#42]
What are your thoughts about `terraform fmt`?
Are you opposed to formatting your module's code for some reason?

**Comment by synhershko** [comment]
I'm not opposed to that - I'm just not nitpicking on formatting and am currently using IntelliJ IDEA when working with terraform.

What difference does this formatting make?

**Comment by kostyrev** [comment]
It makes the code more readable.
