### ISSUE TITLE
EC2 check does not work on some instance types

### ISSUE THREAD

**Issue by arshdeeptinna** [BigDataBoutique/elasticsearch-cloud-deploy#43]
Hypervisor uuid check does not work in i3.2xlarge and so packer fails to install discovery-ec2 plugin
Adding following before the check for azure fixed it in me local environment

```
elif [[ `dmidecode --string system-uuid | head -c 3` == "EC2" ]]; then
  # install AWS-specific plugins only if running on AWS
  # see http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/identify_ec2_instances.html
  sudo bin/elasticsearch-plugin install --batch discovery-ec2
  sudo bin/elasticsearch-plugin install --batch repository-s3
```
Maybe we can add this or a better check.

**Comment by synhershko** [comment]
Why would you run packer on such a huge instance? The recommended way is to run packer on a small spot instance and then reuse the image on large instances (like i3.2xlarge)

**Comment by synhershko** [comment]
Fixed via https://github.com/BigDataBoutique/elasticsearch-cloud-deploy/commit/2e2c83a7bedaa4066e9e722919c34ef7fe65ac50
