### ISSUE TITLE
Terraform 0.12 Compatibility, Support for Open Distro, Implement Elasticsearch Best Practices and more

### ISSUE THREAD

**Issue by waynetaylor** [BigDataBoutique/elasticsearch-cloud-deploy#79]
Hi there,

This project is fantastic, well documented and was a great starter for my project. I've seen added to the project and will send over a pull request but wanted to highlight areas of issues or changes i'd like to see:

Issues:
- Minor changes are needed to the project to work with Terraform 0.12. 
- Elasticsearch packer builder needed shell tweaks to support multiple environment variables
- The build is currently adding Python 2.x which is not officially supported from 2020. I see however, based upon usage no real need for it

Enhancements:
- I've added a variable to packer to support Open Distro for Elasticsearch. If true it will install that with the OSS version 
- Likewise to above, same for Kibana
- Userdata.sh template has been enhanced to support open distro for elasticsearch
- Added conditional variable for client nodes to just be elasticsearch client (e.g. no Kibana, Nginx, etc) 
- Elasticsearch best practice documents usage of instance store over EBS. I've made changes here to handle

Work in Progress:
- Move from ELB Classic to ALB
- Add HTTPS. Self signed node creation for clients and then ACM for Load Balancer
- Updates to documentation

**Comment by synhershko** [comment]
Hi there, and thanks for the feedback!

1. TF 0.12 and any tweaks to scripts and installations are highly welcome.

2. We will not accept a PR for adding Open Distro for Elasticsearch. That distro contains infringed code and promotes a psuedo OSS agenda we do not want to support. Please see my write up in https://code972.com/blog/2019/03/116-dont-confuse-awss-open-distro-for-elasticsearch-with-altruism.

3. I believe we had an issue trying to use ALB in the past for this , but we'll definitely accept a working PR for ALB.

**Comment by jederfreitas** [comment]
Is it already available for TF 0.12?

**Comment by synhershko** [comment]
Not yet, will be soon

**Comment by synhershko** [comment]
TF 12 support is introduced in https://github.com/BigDataBoutique/elasticsearch-cloud-deploy/pull/84 which will be merged soon . Any other changes can be submitted as PRs and we will review those. Thanks for all the proposals.
