### ISSUE TITLE
Kibana Image not getting created

### ISSUE THREAD

**Issue by PNMENON** [BigDataBoutique/elasticsearch-cloud-deploy#81]
I am getting this error when creating the Image using packer for Azure

3 error(s) occurred:

* An image_publisher must be specified
* An image_offer must be specified
* An image_sku must be specified

**Comment by shaigbdb** [comment]
Hi @PNMENON , 
I was able to reproduce this.
When creating the Elasticsearch image, you should be getting an image name in the output. You then have to update azure_elasticsearch_image_name before running packer for the Kibana image.
I've updated the Readme file to mention that.
