### ISSUE TITLE
Packer 1.5.4 - "function "clean_ami_name" not defined" error when building amazon-ebs images

### ISSUE THREAD

**Issue by shaigbdb** [BigDataBoutique/elasticsearch-cloud-deploy#83]
clean_ami_name seems to have been replaced by clean_resource_name .
https://github.com/hashicorp/packer/pull/7456
In Packer 1.4.1 the old syntax still works.

**Comment by tsimonyan** [comment]
Fixed in https://github.com/BigDataBoutique/elasticsearch-cloud-deploy/pull/84
